### ISSUE TITLE
Kibana Installation

### ISSUE THREAD

**Issue by craig** [haka-security/hakabana#2]
This is about the installation docs: http://www.haka-security.org/hakabana.html
1. You should can specify a version number or use this as download link: https://download.elasticsearch.org/kibana/kibana/kibana-latest.tar.gz (IMHO people will try the latest version if you guys don't specify one!)
2. For this text: "Note: you may need to edit 'config.js' file and set the elasticsearch address.
   Example: elasticsearch = http://127.0.0.1:9200"
   This might be a bit confusing and should have the fqdn of the host. By default, this is already set in Kibana (elasticsearch: "http://"+window.location.hostname+":9200") so the default is already fine.
3. "Load Kibana dashboard." is pretty unspecific in how to actually do that; hakabana does not show up for me under "Load". I have an empty dashboard and no idea how to continue.

**Comment by craig** [comment]
So this should be the right way of installing it, I guess?
curl -X PUT http://localhost:9200/kibana-int/dashboard/hakabana -d @Hakabana.json
The dashoard is still empty, though.

**Comment by paulfariello** [comment]
Thanks for your comments. I've updated the hakabana page with fixed link and some screenshots on hakabana dashboard loading.

**Comment by paulfariello** [comment]
Yes the `curl -X PUT` is another way to install the hakabana dashboard. But you can also go with the graphical way. Just as the updated page explain it : http://www.haka-security.org/hakabana.html

**Comment by craig** [comment]
FYI: I'm using Kibana-latest (3.1.0), but I don't have the "Advanced" button in the menu. Not sure what's wrong there...

**Comment by craig** [comment]
Just to clarify: it was an issue with the version of elasticsearch I had deployed; after a fresh install of elasticsearch-1.3.4 it now works fine, and I can load the file like you described, the dashboard is shown. Thank you!
