### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by craig** [haka-security/hakabana#3]
There are some issues with the installation docs at http://www.haka-security.org/hakabana.html:
- You need to install to install haka-geoip before haka-elasticsearch
- hakabana-<version>.deb provides /usr/share/haka/hakabana/haka.conf, but haka-<version>.deb provides /etc/haka/haka.conf (with better examples); only haka should provide the config
- /etc/init.d/haka uses /etc/haka/haka.conf (?), not the other file, /etc/default/haka should use DAEMON_OPTS="-c /etc/haka/haka.conf" to make clear which config is used

**Comment by paulfariello** [comment]
Thanks for reporting.
- I'll update the installation doc according to this dependency.
- Hakabana provides its own, specially crafted, haka.conf there is no problem with it.
- It's haka which use /et/haka/haka.conf if none is provided via command line. May be we could add it to /etc/default/haka.
