### ISSUE TITLE
Eleasticsearch issues

### ISSUE THREAD

**Issue by craig** [haka-security/hakabana#4]
Hi,

after a fresh install, the index "hakabana" does not seem to get created, and I get this error in Kibana:
"Oops! IndexMissingException[[hakabana] missing]"
How can I create it? I'm currently using elasticsearch-1.3.4, maybe that version is too new?

I previously had the index, as I had first I set up hakabana with elasticsearch-0.19.12 (which is too old!), but then migrated the data to 1.3.4. The index 'ips' does get created when I start haka, though, and it's rapidly filling with data. So I'm pretty sure my eleasticsearch config is ok.

Sorry for bothering you guys, but I really want to get this to run. :)

**Comment by paulfariello** [comment]
Hi craig,

There is two different index for two different dashboard `hakabana` and `ips`.

The former is aimed to be used with the [hakabana dashboard](https://raw.githubusercontent.com/haka-security/hakabana/develop/dashboard/Hakabana.json) and is created with the `/usr/share/haka/hakabana/config.lua`. 

The latter was created along with our blog post [Visualizing alerts using kibana and elasticsearch](http://www.haka-security.org/blog/2014/09/30/visualizing-alerts-using-kibana-and-elasticsearch.html) and is created by the `alert/elasticsearch` module.

If you want to use both of them in your own configuration you'll have to make sure you require `misc/hakabana` along with the definition of your rules.
For example you could have :

```
local udp = require('protocol/udp')
require('misc/hakabana').initialize{
    elasticsearch = {
        host = "127.0.0.1",
        port = 9200,
    },
    geoip_data = '/usr/share/GeoIP/GeoIP.dat'
}

-- Define your own rule like
haka.rule{
            hook = udp.events.receive_packet,
            eval = function (pkt)
                haka.alert{
                    start_time = pkt.ip.raw.timestamp,
                    description = desc,
                    severity = severity,
                    confidence = confidence,
                    completion = completion,
                    method = {
                        description = method_desc,
                        ref = method_ref
                    },
                    sources = { haka.alert.address(pkt.ip.src) },
                    targets = { haka.alert.address(pkt.ip.dst) }
                }
    end
```

If you still have your problem you can send us your configuration so we can help you debug it.

We are here to help you, so don't be sorry ;)

**Comment by craig** [comment]
I had to add this to /usr/share/haka/sample/stats/stats.lua, then the hakabana index got created again:

```
require('misc/hakabana').initialize{
    elasticsearch = {
        host = "127.0.0.1",
        port = 9200,
    },
    geoip_data = '/usr/share/GeoIP/GeoIP.dat'
}
```

I'm not sure where/when it got created before.
The file /usr/share/haka/hakabana/config.lua seems to be ignored, I had the code in there before...I'm not sure if that's an issue or not?

Thank you!

**Comment by paulfariello** [comment]
`/usr/share/haka/sample/stats/stats.lua` is a sample config that is aimed at outputing some statistics on the stdout.

There is no special needs to add the hakabana module to it but, hey, you have done what Haka is aimed to : create your own config !

By the way, why have you reopen this issue ? Do you still have some issue ?

**Comment by craig** [comment]
I thought you meant that /usr/share/haka/hakabana/config.lua is automatically included by hakabana, which does not seem to be the case.
