### ISSUE TITLE
HTTP not analyzed

### ISSUE THREAD

**Issue by craig** [haka-security/hakabana#5]
My goal is to use hakabana together with haka to give us more visibility of what's happening in our network. For now, I'd like to use the default functionality of hakabana, and later extend it for SMTP and other protocols. DNS queries seem to be properly analyzed. However, all HTTP information is empty. Here is my config:

/usr/share/haka/sample/stats/stats.lua:

```
--------------------------
-- Loading dissectors
--------------------------

require('misc/hakabana').initialize{
    elasticsearch = {
        host = "127.0.0.1",
        port = 9200,
    },
    geoip_data = '/usr/share/GeoIP/GeoIP.dat'
}

require('protocol/ipv4')
require('protocol/tcp')
local http = require('protocol/http')

local tbl = require('stats_utils')

-- Each entry of stats table will store info
-- about http request/response (method, host,
-- resource, status, etc.)
local stats = tbl.new()

--------------------------
-- Setting next dissector
--------------------------

http.install_tcp_rule(80)

--------------------------
-- Recording http info
--------------------------

haka.rule{
    hook = http.events.response,
    eval = function (http, response)
        local request = http.request
        local split_uri = request.split_uri:normalize()
        local entry = {}
        entry.ip = tostring(http.flow.srcip)
        entry.method = request.method
        entry.resource = split_uri.path or ''
        entry.host = split_uri.host or ''
        entry.useragent = request.headers['User-Agent'] or ''
        entry.referer = request.headers['Referer'] or ''
        entry.status = response.status
        table.insert(stats, entry)
    end
}

return stats
```

/etc/haka/haka.conf:

```
[general]
configuration = "/usr/share/haka/sample/stats/stats.lua"

[packet]
module = "packet/pcap"
interfaces = "eth1"

[log]
module = "log/syslog"

[alert]
module = "alert/elasticsearch"

elasticsearch_server = "http://craigs.nice.host:9200"
geoip_database = "/usr/share/GeoIP/GeoIP.dat"
```

Am I doing this wrong? If so, it would be awesome if the example file would work out-of-the box so it's easier for people to set it up and test.

**Comment by paulfariello** [comment]
Ok now I understand what you are trying to do :)

The out-of-the box example is just running haka with `/usr/share/haka/hakabana/haka.conf` just as stated in the install page. But you are right it would be clearer to have the `-c` option in the `/etc/default/haka`.

If you just want hakabana I strongly recommand to use this configuration. Nevertheless if you want to have both hakabana and haka stats config you are in the right way.

Concerning your http issue, 
- can you confirm that the host `craigs.nice.host` is `127.0.0.1` ? because you use both as elasticsearch server.
- I've tried to reproduce with your config and everything is fine. Can you send us a pcap ? (haka-security at arkoon dot net)

**Comment by craig** [comment]
- craigs.nice.host was the fqdn of the machine (which worked, the DB got filled), but I've changed it to 127.0.0.1 now and verified that works, too.
- I've send you a small pcap with a sample request; the mail couldn't got delivered (queue-id: D893FB017BB) but then I got a message back from Mail Delivery System (MAILER-DAEMON@work.netasq.com) that it could't be delivered.

**Comment by paulfariello** [comment]
Hi Craig,

could you try again with the last commit we've pushed on Haka. They should fix some issue with the Elasticsearch module.

Let us know if you still have your issue.

**Comment by craig** [comment]
Previously I've installed via .deb files, setting up the build environment may take a while.
Don't you feel like bumping the package? ;)

**Comment by craig** [comment]
After not getting a reply from you, I've installed haka and hakabana from git, which was a little painful, but worked in the end. I've got it running with the above config, but still nothing for HTTP. The stats for Protocols, Flows, Bandwidth, Open Flows, Locations and DNS Queries work fine, though.

**Comment by craig** [comment]
I used the query that should be done:

`curl -XGET 'http://192.168.100.240:9200/hakabana/_search?pretty' -d '{
  "facets": {
    "terms": {
      "terms": {
        "field": "host",
        "size": 10,
        "order": "count",
        "exclude": []
      },
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "bool": {
                  "should": [
                    {
                      "query_string": {
                        "query": "_type:http"
                      }
                    }
                  ]
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1415201898218,
                          "to": 1415202198218
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}'`

This returns:

`{
  "took" : 127,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 8637461,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "facets" : {
    "terms" : {
      "_type" : "terms",
      "missing" : 0,
      "total" : 0,
      "other" : 0,
      "terms" : [ ]
    }
  }
}`

I'm not sure what else I should supply to troubleshoot the issue.

**Comment by paulfariello** [comment]
Hi Craig,

sorry for the delay. 

I have spotted your issue thanks to the pcap you have sent. It seems that you are working with a vlan on some of your interfaces and they were not supported. I've just added a small support for it. It will be published with our next release (0.2.2) very soon.

But if you want to test it right now you can checkout my personal branch paulfariello/haka@47c8c131d25b735fc1b6c78187843d1e0a334d8c

Regards,

**Comment by craig** [comment]
I've build haka from your branch, but had no luck so far. 
The stats for Protocols, Flows, Bandwidth, Open Flows, Locations and DNS Queries work fine, but nothing HTTP does. :[ 

I have no idea how to troubleshoot this further, and have spent quite some time on haka and hakabana now without results. Should I post some more info?

I also got some crashes like this:

   **\* glibc detected **\* /usr/local/sbin/haka: free(): corrupted unsorted chunks: 0x00007f6d088da160 ***
   ======= Backtrace: =========
   /lib/x86_64-linux-gnu/libc.so.6(+0x76a16)[0x7f6d25543a16]
   /lib/x86_64-linux-gnu/libc.so.6(cfree+0x6c)[0x7f6d255487bc]
   /usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x13722)[0x7f6d23460722]
   /usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x152e7)[0x7f6d234622e7]
   /usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x25129)[0x7f6d23472129]
   /usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x307ae)[0x7f6d2347d7ae]
   /usr/local/lib/haka/libelasticsearch.so.0(+0x2048)[0x7f6d23ced048]
   /usr/local/lib/haka/libelasticsearch.so.0(+0x2573)[0x7f6d23ced573]
   /lib/x86_64-linux-gnu/libpthread.so.0(+0x6b50)[0x7f6d25b37b50]
   /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f6d255a97bd]
   ======= Memory map: ========
   00400000-0040a000 r-xp 00000000 08:02 14008738                           /usr/local/sbin/haka
   0060a000-0060b000 r--p 0000a000 08:02 14008738                              /usr/local/sbin/haka
0060b000-0060c000 rw-p 0000b000 08:02 14008738                              /usr/local/sbin/haka
   01260000-012a2000 rw-p 00000000 00:00 0                                  [heap]
   012a2000-02ebb000 rw-p 00000000 00:00 0                                  [heap]
   400a0000-400c0000 rw-p 00000000 00:00 0 
   4014a000-4016a000 rw-p 00000000 00:00 0 
   403f0000-40410000 rw-p 00000000 00:00 0 
   404b4000-404d4000 rw-p 00000000 00:00 0 
   4076c000-4078c000 rw-p 00000000 00:00 0 
   408ae000-408ce000 rw-p 00000000 00:00 0 
   40924000-40944000 rw-p 00000000 00:00 0 
   40a55000-40a75000 rw-p 00000000 00:00 0 
   40c7d000-40c9d000 rw-p 00000000 00:00 0 
   40d24000-40d44000 rw-p 00000000 00:00 0 
   40db8000-40dd8000 rw-p 00000000 00:00 0 
   40e14000-40e34000 rw-p 00000000 00:00 0 
   40eab000-40eeb000 rw-p 00000000 00:00 0 
   41074000-41094000 rw-p 00000000 00:00 0 
   41410000-41430000 rw-p 00000000 00:00 0 
   41447000-41467000 rw-p 00000000 00:00 0 
   41591000-415d1000 rw-p 00000000 00:00 0 
   415f0000-41610000 rw-p 00000000 00:00 0 
   41709000-41729000 rw-p 00000000 00:00 0 
   4175c000-4177c000 rw-p 00000000 00:00 0 
   41809000-41829000 rw-p 00000000 00:00 0 
   41a87000-41aa7000 rw-p 00000000 00:00 0 
   41b5d000-41b7d000 rw-p 00000000 00:00 0 
   41c3b000-41c5b000 rw-p 00000000 00:00 0 
   41d50000-41d70000 rw-p 00000000 00:00 0 
   41d7b000-41d9b000 rw-p 00000000 00:00 0 
   41e7f000-41e9f000 rw-p 00000000 00:00 0 
   7f6d08000000-7f6d089dd000 rw-p 00000000 00:00 0 
   7f6d089dd000-7f6d0c000000 ---p 00000000 00:00 0 
   7f6d10000000-7f6d11c29000 rw-p 00000000 00:00 0 
   7f6d11c29000-7f6d14000000 ---p 00000000 00:00 0 
   7f6d16b00000-7f6d16b20000 r-xp 00000000 00:00 0 
   7f6d1abe0000-7f6d1b27a000 rw-p 00000000 00:00 0 
   7f6d1b64b000-7f6d1b909000 rw-p 00000000 00:00 0 
   7f6d1b909000-7f6d1b90e000 r-xp 00000000 08:02 8962061                    /lib/x86_64-linux-gnu/libnss_dns-2.13.so
   7f6d1b90e000-7f6d1bb0d000 ---p 00005000 08:02 8962061                    /lib/x86_64-linux-gnu/libnss_dns-2.13.so
   7f6d1bb0d000-7f6d1bb0e000 r--p 00004000 08:02 8962061                    /lib/x86_64-linux-gnu/libnss_dns-2.13.so
   7f6d1bb0e000-7f6d1bb0f000 rw-p 00005000 08:02 8962061                    /lib/x86_64-linux-gnu/libnss_dns-2.13.so
   7f6d1bc82000-7f6d1bc8d000 r-xp 00000000 08:02 8962062                    /lib/x86_64-linux-gnu/libnss_files-2.13.so
   7f6d1bc8d000-7f6d1be8c000 ---p 0000b000 08:02 8962062                    /lib/x86_64-linux-gnu/libnss_files-2.13.so
   7f6d1be8c000-7f6d1be8d000 r--p 0000a000 08:02 8962062                    /lib/x86_64-linux-gnu/libnss_files-2.13.so
   7f6d1be8d000-7f6d1be8e000 rw-p 0000b000 08:02 8962062                    /lib/x86_64-linux-gnu/libnss_files-2.13.so
   7f6d1be8e000-7f6d1be8f000 ---p 00000000 00:00 0 
   7f6d1be8f000-7f6d1c68f000 rw-p 00000000 00:00 0 
   7f6d1c68f000-7f6d1c690000 ---p 00000000 00:00 0 
   7f6d1c690000-7f6d1ce90000 rw-p 00000000 00:00 0 
   7f6d1ce90000-7f6d1ce91000 ---p 00000000 00:00 0 
   7f6d1ce91000-7f6d1d691000 rw-p 00000000 00:00 0 
   7f6d1d691000-7f6d1d692000 ---p 00000000 00:00 0 
   7f6d1d692000-7f6d1de92000 rw-p 00000000 00:00 0 
   7f6d1de92000-7f6d1de93000 ---p 00000000 00:00 0 
   7f6d1de93000-7f6d1e693000 rw-p 00000000 00:00 0 
   7f6d1e693000-7f6d1e694000 ---p 00000000 00:00 0 
   7f6d1e694000-7f6d1ef9a000 rw-p 00000000 00:00 0 
   7f6d1ef9a000-7f6d1efa0000 r-xp 00000000 08:02 14009021                   /usr/local/lib/haka/modules/misc/elasticsearch.so
   7f6d1efa0000-7f6d1f19f000 ---p 00006000 08:02 14009021                   /usr/local/lib/haka/modules/misc/elasticsearch.so
   7f6d1f19f000-7f6d1f1a0000 r--p 00005000 08:02 14009021                   /usr/local/lib/haka/modules/misc/elasticsearch.so
   7f6d1f1a0000-7f6d1f1a1000 rw-p 00006000 08:02 14009021                   /usr/local/lib/haka/modules/misc/elasticsearch.so
   7f6d1f1a1000-7f6d1f1b9000 r-xp 00000000 08:02 14008776                   /usr/local/lib/haka/modules/protocol/tcp.so
   7f6d1f1b9000-7f6d1f3b9000 ---p 00018000 08:02 14008776                   /usr/local/lib/haka/modules/protocol/tcp.so
   7f6d1f3b9000-7f6d1f3ba000 r--p 00018000 08:02 14008776                   /usr/local/lib/haka/modules/protocol/tcp.so
   7f6d1f3ba000-7f6d1f3bb000 rw-p 00019000 08:02 14008776                   /usr/local/lib/haka/modules/protocol/tcp.so
   7f6d1f3bb000-7f6d1f79b000 rw-s 00000000 00:07 9679997                    socket:[9679997]
   7f6d1f79b000-7f6d1f7a0000 r-xp 00000000 08:02 14008780                   /usr/local/lib/haka/modules/protocol/raw.so
   7f6d1f7a0000-7f6d1f99f000 ---p 00005000 08:02 14008780                   /usr/local/lib/haka/modules/protocol/raw.so
   7f6d1f99f000-7f6d1f9a0000 r--p 00004000 08:02 14008780                   /usr/local/lib/haka/modules/protocol/raw.so
   7f6d1f9a0000-7f6d1f9a1000 rw-p 00005000 08:02 14008780                   /usr/local/lib/haka/modules/protocol/raw.so
   7f6d1f9a1000-7f6d1f9dd000 r-xp 00000000 08:02 3866685                    /lib/x86_64-linux-gnu/libpcre.so.3.13.1
   7f6d1f9dd000-7f6d1fbdd000 ---p 0003c000 08:02 3866685                    /lib/x86_64-linux-gnu/libpcre.so.3.13.1
   7f6d1fbdd000-7f6d1fbde000 rw-p 0003c000 08:02 3866685                    /lib/x86_64-linux-gnu/libpcre.so.3.13.1
   7f6d1fbde000-7f6d1fbe4000 r-xp 00000000 08:02 14008757                   /usr/local/lib/haka/modules/regexp/pcre.so
   7f6d1fbe4000-7f6d1fde3000 ---p 00006000 08:02 14008757                   /usr/local/lib/haka/modules/regexp/pcre.so
   7f6d1fde3000-7f6d1fde4000 r--p 00005000 08:02 14008757                      /usr/local/lib/haka/modules/regexp/pcre.so
   7f6d1fde4000-7f6d1fde5000 rw-p 00006000 08:02 14008757                   /usr/local/lib/haka/modules/regexp/pcre.so
   7f6d1fde5000-7f6d1fde9000 r-xp 00000000 08:02 14008752                   /usr/local/lib/haka/modules/packet/pcap.so
   7f6d1fde9000-7f6d1ffe8000 ---p 00004000 08:02 14008752                   /usr/local/lib/haka/modules/packet/pcap.so
   7f6d1ffe8000-7f6d1ffe9000 r--p 00003000 08:02 14008752                   /usr/local/lib/haka/modules/packet/pcap.so
   7f6d1ffe9000-7f6d1ffea000 rw-p 00004000 08:02 14008752                   /usr/local/lib/haka/modules/packet/pcap.so
   7f6d1ffea000-7f6d1fffb000 r-xp 00000000 08:02 13681293                   /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
   7f6d1fffb000-7f6d201fa000 ---p 00011000 08:02 13681293                   /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0

**Comment by craig** [comment]
Do you need more info? I'd really like to get the HTTP part to work.

**Comment by craig** [comment]
It now works with the latest versions from git. :)
