### ISSUE TITLE
kibana 4 support

### ISSUE THREAD

**Issue by jiamo** [haka-security/hakabana#8]
In readme : 

On the Kibana page, you need to import the predefined dashboard that is available at <install prefix>/share/haka/hakabana/dashboard/Hakabana.json. This dashboard will report various information about the packets and connections seen on the network.

How to do this in kibana 4?

**Comment by mtalbi** [comment]
Unfortunately, you cannot import dashboard from Kibana 3 to Kibana 4. You need to recreate the hakabana dashboard in Kibana 4.
